{% set name = "uv-build" %}
{% set version = "0.9.7" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/{{ name|replace('-', '_') }}-{{ version }}.tar.gz
  sha256: 88bfe1ad6df778338e4cb6d59bf8d206d6c13d42a9f6000a7a0dbc6cd3435315

build:
  number: 0
  skip: true  # [py<38]
  script:
    # larger updated load commands do not fit … use -headerpad or -headerpad_max_install_names
    # no space for load-cmd → install_name_tool can't inject rpath
    - export RUSTFLAGS="${RUSTFLAGS} -C link-arg=-Wl,-headerpad_max_install_names"  # [osx]
    - {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
    - cargo-bundle-licenses --format yaml --output THIRDPARTY.yml

requirements:
  build:
    - {{ stdlib('c') }}
    - {{ compiler('c') }}
    - {{ compiler('rust') }}
    - cargo-bundle-licenses
  host:
    - python
    - pip
    - maturin >=1.0,<2.0
    # bin/uv-build: Needed DSO lib/liblzma.so.5
    - xz {{ xz }}
  run:
    - python

test:
  imports:
    - uv_build
  requires:
    - pip
  commands:
    - pip check
    - python -c "from importlib.metadata import version; assert(version('{{ name }}')=='{{ version }}')"

about:
  home: https://pypi.org/project/uv
  summary: An extremely fast Python package and project manager, written in Rust.
  description: An extremely fast Python package and project manager, written in Rust.
  license: Apache-2.0 OR MIT
  license_family: OTHER
  license_file:
    - LICENSE-MIT
    - LICENSE-APACHE
    - THIRDPARTY.yml
  dev_url: https://github.com/astral-sh/uv
  doc_url: https://docs.astral.sh/uv

extra:
  recipe-maintainers:
    - isuruf
