{% set name = "uv_build" %}
{% set version = "0.6.14" %}

package:
  name: uv-build
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/uv_build-{{ version }}.tar.gz
  sha256: 2fbf83d9fab2b8759b3f38ec9d8068c1a2b29450794dda4ab1929a419577b6ba

build:
  number: 0

requirements:
  build:
    - {{ compiler('c') }}
    - {{ stdlib('c') }}
    - {{ compiler('rust') }}
    - cargo-bundle-licenses
    - python                                        # [build_platform != target_platform]
    - cross-python_{{ target_platform }}            # [build_platform != target_platform]
  host:
    - python
    - maturin >=1.0,<2.0
    - pip
  run:
    - python

test:
  imports:
    - uv_build
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://pypi.org/project/uv/
  summary: The uv build backend
  license: Apache-2.0 AND MIT AND BSD-2-Clause
  license_file:
    - LICENSE-MIT
    - LICENSE-APACHE
    - crates/uv-pep440/License-Apache
    - crates/uv-pep440/License-BSD
    - crates/uv-build/LICENSE-MIT
    - crates/uv-build/LICENSE-APACHE
    - crates/uv-pep508/License-Apache
    - crates/uv-pep508/License-BSD
    - THIRDPARTY.yml

extra:
  recipe-maintainers:
    - isuruf
